#!/bin/bash -e

if [ ! -f pom.xml ]; then
	echo "This must be run from the project root." >&2
	exit 1
fi

REGISTRY="https://www.iana.org/assignments/http-status-codes/http-status-codes.txt"
TMP="target/scripts/http-status-codes.txt"
mkdir -p `dirname $TMP`

if [ ! -f $TMP ]; then
	curl $REGISTRY > $TMP
fi

OUT="src/main/resources/boom-default-bundles/httpstatus.properties"
mkdir -p `dirname $OUT`
egrep -i "^ +[0-9]{3} +[a-z]" $TMP | sed -e 's/ *\[.*//' -e 's/^ \+/SC_/' -e 's/ \+/=/' -e 's/ *$//' > $OUT

